getenv:getenv.o
	cc -o getenv getenv.o
getenv.o:getenv.c
	cc -c getenv.c
clean:
	rm getenv.o getenv

myset:myset.o
	cc -o myset myset.o
myset.o:myset.c
	cc -c myset.c
clean:
	rm myset.o myset

clean:
	rm *.o
